MODULES = {
1: {
 "title": "Module 1",
 "objectives": [
  "Distinguish between Destiny Library Manager and Destiny Resource Manager and identify which platform handles a given task.",
  "Navigate the four Back Office tabs (Catalog, Circulation, Reports, Admin) and locate a specified feature within each.",
  "Log in via SSO and troubleshoot a basic \"Invalid Username\" claim-mismatch error.",
  "Identify the correct Destiny mobile app (Discover, Back Office, or VersaScan) for a given staff or student task.",
  "Explain how Destiny's WCAG 2.1 AA accessibility features support students who use screen readers or keyboard-only navigation.",
 ],
 "mcq": [
  ("Which Back Office tab would a librarian use to check out a class set of laptops to a teacher?",
   ["A. Catalog","B. Circulation","C. Reports","D. Admin"], "B"),
  ("A staff member gets an \"Invalid Username\" error when logging in through Google SSO. What should be checked first?",
   ["A. The patron's fine balance","B. The domain filter and Destiny Field mapping","C. The Report Builder 2.0 schedule","D. The WebPath Express settings"], "B"),
  ("Which app is required for a librarian to convert a smartphone into a wireless circulation desk?",
   ["A. Destiny Discover App","B. Destiny Back Office App","C. Follett Remote","D. Collections by Destiny"], "B"),
  ("Which standard governs Destiny's accessibility conformance for screen readers and keyboard navigation?",
   ["A. FERPA","B. COPPA","C. WCAG 2.1 AA","D. OneRoster"], "C"),
 ],
 "short_answer": [
  ("A new librarian cannot remember which tab houses Report Builder 2.0. Walk them through how to find it and describe one thing they could do there.",
   "Report Builder 2.0 lives under the Reports tab; the librarian can build, preview, automate, and export a custom report (e.g., a filtered circulation-statistics query)."),
  ("A parent using a Chromebook says Destiny Discover looks broken on their child's tablet at home. What two things would you check based on system requirements?",
   "Confirm the device/OS is within supported ranges (e.g., iOS 15-18+/Android 7.0-15.0+ with Chrome or Safari 15.4+) and confirm the browser being used is on the supported list; also check display resolution meets the 1024x768 minimum."),
 ],
 "checklist": [
  "Logged into Destiny Back Office and toured all four tabs without assistance.",
  "Correctly identified the Catalog, Circulation, Reports, and Admin tab for three sample tasks given by the supervisor.",
  "Located and opened Report Builder 2.0.",
  "Demonstrated troubleshooting an SSO login error using the correct navigation path.",
  "Can name the three Destiny mobile apps and their primary use cases.",
 ],
},
2: {
 "title": "Module 2",
 "objectives": [
  "Differentiate district-level and site-level administrative roles within Destiny's security hierarchy.",
  "Configure a custom access level with appropriate permissions across the four sub-tabs (Library Materials, Resources, Patrons, General).",
  "Explain why FERPA/COPPA compliance requires restricting access to patron PII by role.",
  "Set up a self-checkout station with privacy protections enabled.",
  "Predict the outcome of a district \"Push\" operation on a site's local access-level settings.",
 ],
 "mcq": [
  ("Which default access level grants read-only catalog search without a personal profile?",
   ["A. Patron","B. Staff","C. Guest","D. Teacher"], "C"),
  ("A district administrator wants every school to use identical permission checkmarks with no local override. Which control model achieves this?",
   ["A. Setup Initial Access Levels (Site Autonomy)","B. District Defined Access Levels Applied to All Sites (Central Control)","C. Push Conflict Override only","D. LDAP Directory Attribute Mapping"], "B"),
  ("What does enabling \"Display limited circulation information (Library only)\" on a self-checkout station do?",
   ["A. Hides all patron names","B. Masks surnames, addresses, and fine histories on-screen","C. Disables checkout entirely for guests","D. Extends the idle timeout to 5 minutes"], "B"),
  ("When a district executes a Push operation, what is preserved at the site level?",
   ["A. Nothing; all local settings are overwritten","B. Site-created custom access levels and local resource groups","C. Only the Guest access level","D. The site's LDAP configuration"], "B"),
 ],
 "short_answer": [
  ("A substitute teacher only needs to see which items are checked out to their homeroom, nothing else. What access-level principle should guide how you configure their permissions, and why?",
   "Apply the principle of least privilege / role-based privacy safeguards: grant only \"View library items out\" without access to full student demographic profiles or admin logs, since unrestricted access exposes PII the substitute doesn't need."),
  ("Explain the difference between LDAP-based automated role provisioning and manually assigning access levels, and give one operational benefit of the automated approach.",
   "LDAP/SSO provisioning maps directory attributes (e.g., OU=Teachers) directly to Destiny access levels/patron types automatically at login or bulk import; benefit: when a staff member's AD status changes, Destiny updates permissions automatically at next login, eliminating manual role adjustments and reducing the risk of stale/incorrect access."),
 ],
 "checklist": [
  "Audited enabled permissions for Teacher, Staff, and Patron across all four sub-tabs.",
  "Created a custom \"Student Library Assistant\" access level with an appropriate idle timeout.",
  "Assigned the new access level to a test patron and verified updated privileges.",
  "Can explain the FERPA/COPPA rationale for restricting patron-history access.",
  "Correctly described what a district Push operation does and does not overwrite.",
 ],
},
3: {
 "title": "Module 3",
 "objectives": [
  "Create and configure an individual patron record, including barcode, District ID, and Patron Type.",
  "Choose the correct bulk-import method (Direct Web Import, PIC, or Scheduled Update) for a given SIS scenario.",
  "Diagnose and resolve at least two common patron-import job errors.",
  "Link class schedules to course rosters and explain the purpose of the \"Currently Teaching\" flag.",
  "Apply data-retention rules correctly when inactivating vs. deleting a withdrawn or graduated student record.",
 ],
 "mcq": [
  ("Which patron flag must be enabled on a faculty account to allow class schedule assignments and textbook transfers?",
   ["A. \"Currently Teaching\"","B. \"District ID Required\"","C. \"Self-Checkout\"","D. \"Guest Access\""], "A"),
  ("A district needs to convert a PowerSchool CSV export into Destiny-compliant XML with custom field mapping. Which tool is used?",
   ["A. Direct Web Import","B. Patron Import Converter (PIC)","C. Class Import Converter (CIC)","D. Report Builder 2.0"], "B"),
  ("An import job fails with \"Required Field 'District ID' is Blank.\" What is the most likely cause?",
   ["A. The district disabled SSO","B. Incoming CSV rows lack unique student IDs while the district requires them","C. The barcode range has been exhausted","D. The class schedule wasn't linked to a course"], "B"),
  ("Under the automated senior purge, what happens to a graduated student's record if they have unpaid fines?",
   ["A. It is purged immediately regardless of fines","B. It is excluded from the automatic purge unless outstanding-transaction deletion is separately enabled","C. It is converted to a Guest account","D. It is merged with a sibling's record"], "B"),
 ],
 "short_answer": [
  ("A teacher's roster import keeps failing with a \"Duplicate Barcode / Username Conflict.\" What are two ways to resolve this?",
   "Set the PIC duplicate rule to \"Merge incoming records,\" or manually resolve the specific barcode exception directly in the Job Summary log."),
  ("Why does Destiny distinguish between \"inactivating\" and \"deleting\" a withdrawn student's account? Give one privacy or audit reason for each.",
   "Inactivating preserves circulation history and fine records for audit purposes while revoking borrowing privileges; deleting removes the record, so districts balance audit/financial needs against reading-privacy retention limits (e.g., purging historical checkout logs after 1-3 years)."),
 ],
 "checklist": [
  "Manually created a test teacher account with \"Currently Teaching\" enabled and correct site association.",
  "Successfully uploaded a sample patron CSV and reviewed the Job Summary for errors.",
  "Linked a class set of resources to an active course section.",
  "Correctly explained the difference between inactivation and deletion of a patron record.",
  "Identified the appropriate SIS integration path (PowerSchool, Infinite Campus, or Skyward/Aeries) for a given scenario.",
 ],
},
4: {
 "title": "Module 4",
 "objectives": [
  "Search Alliance Plus and Z39.50 sources before creating a manual catalog record, in order to prevent duplicates.",
  "Select the appropriate cataloging tool (Easy Editor or MARC Editor) for a given title.",
  "Apply the CREW/MUSTIE framework to evaluate a physical item as a weeding candidate.",
  "Execute an individual and a batch weed in Destiny, including the correct Weeding Reason and Disposal Method.",
  "Correctly catalog a multi-volume series using MARC tags 490/830 or 245 $n/$p as appropriate.",
 ],
 "mcq": [
  ("Before manually creating a new title record, what should a librarian always do first?",
   ["A. Assign a call number","B. Search Alliance Plus or a Z39.50 source to check for an existing record","C. Print spine labels","D. Run the Weeding Log report"], "B"),
  ("A book is factually outdated in a way that could mislead students, but otherwise in good physical condition. Which MUSTIE criterion applies?",
   ["A. Ugly","B. Superseded","C. Misleading","D. Trivial"], "C"),
  ("Which MARC tag holds the authorized uniform series title and volume number (e.g., \"Percy Jackson ; bk. 1\")?",
   ["A. Tag 245","B. Tag 490","C. Tag 830","D. Tag 650"], "C"),
  ("What does enabling \"When the last copy of a title is deleted, remove the title from the library's collection\" do?",
   ["A. Automatically purges orphaned MARC records with no remaining copies","B. Deletes all copies of every title in that sublocation","C. Disables the Weeding Log report","D. Converts the title to a digital-only record"], "A"),
 ],
 "short_answer": [
  ("A shipment of retrospective titles is being bulk-imported via MARC files. Explain the difference between Strict and Relaxed title-matching rules and when you'd use each.",
   "Strict matching requires exact matches on standard numbers (ISBN/ISSN/LCCN) plus title and material type, preventing duplicates when standard numbers are reliable; relaxed matching falls back to Title/Author/Publication Date/Material Type when standard numbers are missing, useful for older or less-standardized records."),
  ("You are cataloging a 6-volume encyclopedia set where each volume covers different content but shares one title. Which multivolume cataloging approach would you choose, and why?",
   "Single Bibliographic Record with MARC 505 contents tag listing volume titles and separate copy barcodes per volume — appropriate when the volumes share one overarching title/author, rather than creating separate bib records (which is reserved for volumes with significantly different titles/authors)."),
 ],
 "checklist": [
  "Sourced a title from Alliance Plus or a Z39.50 server and added a physical copy with barcode and call number.",
  "Created a sublocation and assigned copy categories correctly.",
  "Performed a sample individual weed with correct Weeding Reason and Disposal Method selected.",
  "Correctly applied MUSTIE criteria to a sample weeding scenario presented by the supervisor.",
  "Cataloged a multi-volume or series title using the correct MARC tag approach.",
 ],
},
5: {
 "title": "Module 5",
 "objectives": [
  "Perform a standard checkout, check-in, and renewal transaction at the circulation desk.",
  "Place a hold, monitor the hold queue, and process an interlibrary loan request.",
  "Configure and use offline circulation via Follett Remote during a network outage.",
  "Set up a self-checkout kiosk with an appropriate privacy timeout.",
  "Apply the correct textbook loan period (class vs. interval) for a given course scenario.",
 ],
 "mcq": [
  ("Which tool converts smartphones/tablets equipped with the Back Office App into wireless circulation desks?",
   ["A. Follett Remote","B. VersaScan","C. Collections by Destiny","D. Report Builder 2.0"], "B"),
  ("A librarian needs to check out barcodes while the network is down. What file type does Follett Remote generate for later upload?",
   ["A. .xml","B. .csv","C. .txt","D. .pdf"], "C"),
  ("Why does Destiny automatically suppress same-day textbook checkins from circulation statistics?",
   ["A. To save server storage","B. To avoid inflating official circulation counts","C. Because same-day returns are against policy","D. To trigger an automatic fine"], "B"),
  ("What idle-timeout range does Destiny recommend for a self-checkout station to protect student privacy between patrons?",
   ["A. 1-5 minutes","B. 15-30 seconds","C. 1 hour","D. No timeout needed"], "B"),
 ],
 "short_answer": [
  ("A teacher wants to check out an entire class set of literature kits to their roster in one transaction. What Destiny feature enables this, and what module dependency does it rely on (from Module 3)?",
   "Class Set Checkouts (under Circulation), which relies on the class schedule/roster being correctly linked via Update Classes and the teacher's \"Currently Teaching\" flag being enabled, as covered in Module 3."),
  ("Describe the workflow for uploading offline circulation transactions once network connectivity is restored, including what the Job Manager produces.",
   "Go to Circulation > Offline Circulation, browse for the saved .txt transaction file, specify transaction/due-date overrides, and click Upload; Job Manager processes files oldest-first and generates an audit Job Summary."),
 ],
 "checklist": [
  "Performed a simulated checkout, renewal, and check-in on test items.",
  "Placed a hold and located the active hold queue.",
  "Initiated a sample interlibrary loan request.",
  "Demonstrated the offline circulation upload workflow (or explained it if sandbox limited).",
  "Correctly distinguished class-based vs. interval-based textbook loan periods.",
 ],
},
6: {
 "title": "Module 6",
 "objectives": [
  "Initiate a scoped library inventory using call number, sublocation, or resource type filters.",
  "Execute an inventory using live and/or offline (VersaScan/Follett Remote) barcode scanning.",
  "Correctly process unaccounted-for items, including marking items Lost and linking results to weeding.",
  "Sequence a year-end inventory using the four-phase checklist (Recall & Freeze, Database Prep, Physical Scanning, Reconciliation).",
  "Interpret a Resource Value Report, including how straight-line depreciation is calculated.",
 ],
 "mcq": [
  ("Which phase of the year-end inventory checklist involves freezing interlibrary loans and issuing recall notices?",
   ["A. Phase 1 - Recall & Freeze","B. Phase 2 - Database Prep","C. Phase 3 - Physical Scanning","D. Phase 4 - Reconciliation & Finalization"], "A"),
  ("An item is marked \"Unaccounted For\" at the end of an inventory and the librarian selects \"Track as weeded.\" What happens?",
   ["A. The item is restored to Available status","B. The record transfers to the Weeding Log, preserving replacement valuation data","C. The patron who last checked it out is fined automatically","D. The item's call number is reassigned"], "B"),
  ("What is the correct straight-line depreciation formula Destiny uses for Resource Manager assets?",
   ["A. Purchase Price x Depreciable Life","B. (Purchase Price - Salvage Value) / Depreciable Life (Years)","C. Purchase Price / Current Year","D. Replacement Cost - Purchase Price"], "B"),
  ("Which method allows collecting barcode scans wirelessly without being tethered to a Destiny workstation during an inventory?",
   ["A. Report Builder 2.0","B. VersaScan or Follett Remote","C. Class Import Converter","D. Collections by Destiny"], "B"),
 ],
 "short_answer": [
  ("Why does Follett recommend rolling, section-by-section inventories during Fall/Winter rather than saving the whole collection for one spring audit?",
   "Rolling inventories maintain continuous collection accuracy without requiring a full library closure, spreading the workload and catching discrepancies earlier rather than in one disruptive year-end event."),
  ("During a physical shelf-scan, a librarian finds several damaged, outdated books. Describe the correct workflow connecting this discovery to both inventory and weeding processes.",
   "Pull the items, evaluate them against CREW MUSTIE criteria, add them to a temporary Resource List if needed, then batch-delete them under Catalog > Update Copies > Batch Delete with the appropriate weeding reason — this links the physical audit finding directly into the weeding workflow from Module 4."),
 ],
 "checklist": [
  "Initiated a partial-section inventory with correct call number/sublocation limits.",
  "Practiced scanning barcodes and confirmed items moved to Accounted For status.",
  "Reviewed the Unaccounted For report and correctly marked a test item Lost.",
  "Can explain the four-phase year-end inventory checklist in order.",
  "Correctly described how straight-line depreciation is calculated for a Resource Manager asset.",
 ],
},
7: {
 "title": "Module 7",
 "objectives": [
  "Generate a preconfigured circulation, overdue/fine, or title/copy-list report from the correct Reports menu location.",
  "Build and export a custom query using Report Builder 2.0.",
  "Schedule an automated recurring report (e.g., weekly overdue digest).",
  "Curate an EE/TOK Resource List and export MLA/APA-formatted citations for IB accreditation purposes.",
  "Identify the correct export path (XML/Excel, OneRoster API, or command-line utility) for a given external BI or SIS integration need.",
 ],
 "mcq": [
  ("Which tool would a librarian use to build a custom, drag-and-drop query across Library Manager and Resource Manager data?",
   ["A. Collections by Destiny","B. Report Builder 2.0","C. Patron Import Converter","D. WebPath Express"], "B"),
  ("A librarian needs a list of titles with zero circulations over the past three years to plan weeding. Which report category covers this?",
   ["A. Overdue & Fine Notices","B. Title & Copy Lists (uncirculated items)","C. Collection Statistics — Historical","D. Resource Value Report"], "B"),
  ("Which export format allows Report Builder 2.0 data to be ingested directly into tools like Power BI or Tableau?",
   ["A. .txt only","B. XML or native Excel (.xlsx)","C. PDF only","D. MARC 21 only"], "B"),
  ("What is the primary purpose of curating a Resource List for an IB Extended Essay topic?",
   ["A. To automatically generate MLA/APA citations and track source-diversity for accreditation audits","B. To restrict which students can check out fiction","C. To calculate patron fines","D. To configure the self-checkout kiosk"], "A"),
 ],
 "short_answer": [
  ("A principal wants overdue notices emailed automatically every Monday without staff manually running the report. What Destiny 23.5/24.0 feature enables this, and where is it configured?",
   "Report Builder 2.0's automated report scheduling feature, configured under Reports > Report Builder, allows recurring reports (e.g., weekly overdue digests) to be scheduled and sent automatically to administrative email inboxes."),
  ("Explain how TitleWise Collection Evaluation supports IB accreditation reporting beyond simple circulation counts.",
   "TitleWise submits catalog data to produce collection age, subject balance, and diversity gap analyses — giving accreditation boards evidence of curriculum-aligned, current, and balanced holdings, not just circulation activity."),
 ],
 "checklist": [
  "Built a custom query in Report Builder 2.0, previewed results, and exported to Excel.",
  "Ran a homeroom overdue-notice report and previewed the PDF output.",
  "Generated an uncirculated-titles report to identify weeding candidates.",
  "Can explain how to curate and export an EE/TOK Resource List with citations.",
  "Correctly identified the right export path (XML/Excel, OneRoster, or command-line) for a sample integration scenario.",
 ],
},
8: {
 "title": "Module 8",
 "objectives": [
  "Customize the Destiny Discover homepage ribbon layout and apply a student-facing theme.",
  "Build a thematic Collection combining catalog titles, web links, and video resources for a classroom unit.",
  "Explain the accessibility features (text-to-speech, dyslexia-friendly fonts, WCAG compliance) of the integrated eBook reader.",
  "Configure LTI integration so Destiny Discover content can be embedded in Canvas or Google Classroom.",
  "Set up parent-portal access using synchronized guardian contact fields from the SIS.",
 ],
 "mcq": [
  ("Where would a librarian go to reorder homepage ribbons and enable \"Featured Collections\" in Destiny Discover?",
   ["A. Admin > Access Levels","B. Catalog > Search Setup > Digital Setup","C. Circulation > Self-Checkout","D. Reports > Report Builder"], "B"),
  ("Which feature lets a teacher build a curated board of catalog titles, web links, and videos for a research unit?",
   ["A. Destiny Engage","B. Collections by Destiny","C. WebPath Express","D. Resource Value Report"], "B"),
  ("What accessibility feature is built directly into the Follett eBook reader?",
   ["A. Barcode scanning","B. Text-to-speech, adjustable font size, and dyslexia-friendly fonts","C. Automated overdue notices","D. LDAP role provisioning"], "B"),
  ("How does a Canvas or Schoology course get access to embedded Destiny library titles?",
   ["A. Through LTI integration configured under Setup > Sites > SSO Configuration","B. By manually emailing PDF catalogs to teachers","C. Through the Patron Import Converter","D. Through the Weeding Log report"], "A"),
 ],
 "short_answer": [
  ("A parent asks how they can see their child's due dates and fines from home. Walk through where that data originates and how the parent accesses it.",
   "Primary/secondary guardian email fields, synced from the SIS (e.g., PowerSchool or Skyward) into Destiny's Email 1/Email 2 patron fields, power the Destiny Parent Portal; the parent logs in at the portal with their registered email to view active loans, due dates, hold queues, and fines."),
  ("A teacher wants students to see library resources without leaving Google Classroom. What two sharing options does Destiny support for this, and how do they differ?",
   "One-click sharing of catalog items/Collections directly to Google Classroom, or exporting a Thin Common Cartridge file for import into an LMS course module — the first is a direct live share, the second is a portable file-based import."),
 ],
 "checklist": [
  "Reordered homepage ribbons and enabled Featured Collections in a test/sandbox environment.",
  "Built a thematic Collection with at least 3 catalog titles and 2 external resources.",
  "Opened a Follett eBook and tested font/accessibility adjustments.",
  "Can explain the LTI setup path for Canvas/Schoology integration.",
  "Correctly described how Parent Portal access is provisioned from SIS data.",
 ],
},
9: {
 "title": "Module 9",
 "objectives": [
  "Locate and interpret a Destiny release Readiness Kit before a district upgrade.",
  "Use Follett Community and Follett Academy/myTrailhead for ongoing professional development.",
  "Access context-sensitive in-product help and submit a technical support ticket through the correct channel.",
  "Explain the difference between cloud-managed and on-premise Destiny backup/disaster-recovery procedures.",
  "Apply the change-management framework (readiness review, staff training, sandbox practice) before a live software rollout.",
 ],
 "mcq": [
  ("Where should a librarian go for context-sensitive, in-product help on any Destiny page?",
   ["A. The Help link in the top header","B. Admin > Site Configuration","C. Follett Academy only","D. The Works Cited page"], "A"),
  ("What is the emergency escalation window for a Priority 1 (system-down) support issue?",
   ["A. Business hours only (7am-7pm ET)","B. 24/7 emergency escalation","C. Next business day","D. Only via email"], "B"),
  ("For cloud-hosted Destiny customers, how is disaster recovery primarily handled?",
   ["A. Manual weekly exports by the librarian","B. Automatically managed nightly cloud backups with off-site geo-redundancy","C. On-premise SQL Server transaction logs only","D. No backup is provided for cloud customers"], "B"),
  ("What should be reviewed before a district rolls out a new Destiny version like 24.0?",
   ["A. Only the invoice","B. The version's Readiness Kit and maintenance downtime notices","C. The Weeding Log report","D. The patron barcode range"], "B"),
 ],
 "short_answer": [
  ("A district is about to upgrade from 23.5 to 24.0. Outline the recommended change-management sequence from readiness review through go-live.",
   "Review the Readiness Kit, publish maintenance downtime notices and communicate feature updates to leadership, use Follett Academy/myTrailhead trails and QRGs for staff training, conduct hands-on sandbox practice, then deploy live."),
  ("Explain the difference between Follett Community and Follett Academy, and when a librarian would use each.",
   "Follett Community is the user forum/announcements/QRG/idea-board hub for news and peer discussion; Follett Academy (myTrailhead) is the self-paced, gamified training platform with badges/certificates — use Community to stay current on releases and Academy to build or certify skills."),
 ],
 "checklist": [
  "Registered on Follett Community and located the current Readiness Kit.",
  "Used the in-product Help link to look up a topic and reviewed the guide.",
  "Selected a Follett Academy training trail and set a personal learning goal.",
  "Can explain the difference between cloud-managed and on-premise backup procedures.",
  "Correctly sequenced the change-management steps for a version upgrade.",
 ],
},
}
